
name: Backup to S3

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Bare clone
        timeout-minutes: 2
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          gh repo clone "${{ github.repository }}" "$HOME/${{ github.event.repository.name }}" -- --bare
          cd "$HOME/${{ github.event.repository.name }}"
          git gc

      - name: Archive repository
        timeout-minutes: 2
        run: |-
          zip -r "$HOME/${{ github.event.repository.name }}-$(date +%Y%m%dT%H%M%S).zip" "$HOME/${{ github.event.repository.name }}"

      - name: Upload archive to S3
        timeout-minutes: 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_REGION: ${{ secrets.REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        run: |-
          aws s3 cp $HOME/${{ github.event.repository.name }}-*.zip s3://${{ secrets.BUCKET }}/${{ github.event.repository.name }}/
