name: Backup to S3

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Backup repository to S3
        uses: ataraxia937/backup-to-s3@v1
        with:
          s3-bucket: ${{ secrets.BUCKET }}
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.REGION }}
